<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class HistoriaClinicaRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'enfermero_id' => 'required|numeric',
            'chofer_id' => 'required|numeric',
            /* 'medico_id' => 'required|numeric',
             'cliente_id' => 'required|numeric',*/
            'movil' => 'required|numeric',
            'numero_llamado' => 'required|numeric',
            'clave_salida' => 'required|numeric',
            'convenio' => 'required|string',
            'motivo_consulta' => 'nullable|string',
            'medicacion' => 'nullable|string',
            'antecedentes_diabetes' => 'boolean',
            'antecedentes_asma' => 'boolean',
            'antecedentes_epoc' => 'boolean',
            'antecedentes_neoplasia' => 'boolean',
            'antecedentes_hta' => 'boolean',
            'antecedentes_cisquemica' => 'boolean',
            'antecedentes_insufcard' => 'boolean',
            'antecedentes_arritmia' => 'boolean',
            'antecedentes_icvasc' => 'boolean',
            'antecedentes_ave' => 'boolean',
            'antecedentes_alergias' => 'boolean',
            'antecedentes_otros' => 'boolean',
            'antecedentes_ninguno' => 'boolean',
            'antecedentes_texto' => 'string',
            'pielmucosa_palidez' => 'boolean',
            'pielmucosa_cianosis' => 'boolean',
            'pielmucosa_sudoracion' => 'boolean',
            'pielmucosa_livideces' => 'boolean',
            'pielmucosa_ictericia' => 'boolean',
            'pielmucosa_edemas' => 'boolean',
            'pielmucosa_normal' => 'boolean',
            'pielmucosa_texto' => 'nullable|string',
            'neurologico_pupilas' => 'nullable|string',
            'neurologico_smening' => 'nullable|string',
            'neurologico_pcranean' => 'nullable|string',
            'neurologico_sespinal' => 'nullable|string',
            'neurologico_glascow_hora1' => 'date_format:H:i',
            'neurologico_glascow_hora2' => 'date_format:H:i',
            'neurologico_glascow_o1' => 'integer|between:1,15',
            'neurologico_glascow_o2' => 'integer|between:1,15',
            'neurologico_glascow_v1' => 'integer|between:1,15',
            'neurologico_glascow_v2' => 'integer|between:1,15',
            'neurologico_glascow_m1' => 'integer|between:1,15',
            'neurologico_glascow_m2' => 'integer|between:1,15',
            'neurologico_normal' => 'boolean',
            'cardiovascular_taquicardia' => 'boolean',
            'cardiovascular_bradicardia' => 'boolean',
            'cardiovascular_rirregular' => 'boolean',
            'cardiovascular_galope' => 'boolean',
            'cardiovascular_parocardioresp' => 'boolean',
            'cardiovascular_soplos' => ['required', Rule::in(config('data.soplos')),],
            'cardiovascular_iyugular' => 'boolean',
            'cardiovascular_edemasmmii' => 'boolean',
            'cardiovascular_normal' => 'boolean',
            'cardiovascular_angor' => 'boolean',
            'cardiovascular_pulsoperifer' => 'nullable|string',
            'cardiovascular_otros' => 'nullable|string',
            'respiratorio_tbronquitis' => 'boolean',
            'respiratorio_puntadadelado' => 'boolean',
            'respiratorio_hemopitises' => 'boolean',
            'respiratorio_cextrano' => 'boolean',
            'respiratorio_texto' => 'nullable|string',
            'respiratorio_normal' => 'boolean',
            'respiratorio_disnea' => 'boolean',
            'respiratorio_estcrep' => ['required', Rule::in(config('data.respiratorio')),],
            'respiratorio_estscrep' => ['required', Rule::in(config('data.respiratorio')),],
            'respiratorio_sibilancias' => ['required', Rule::in(config('data.respiratorio')),],
            'respiratorio_roncus' => ['required', Rule::in(config('data.respiratorio')),],
            'respiratorio_mvausente' => ['required', Rule::in(config('data.respiratorio')),],
            'respiratorio_soplo' => ['required', Rule::in(config('data.respiratorio')),],
            'abdomen_nauseas' => 'boolean',
            'abdomen_vomitos' => 'boolean',
            'abdomen_dolorpal' => 'boolean',
            'abdomen_distabd' => 'boolean',
            'abdomen_defensa' => 'boolean',
            'abdomen_rha' => ['required', Rule::in(config('data.rha')),],
            'abdomen_hemorragdig' => 'boolean',
            'abdomen_hernia' => 'boolean',
            'abdomen_hepaton' => 'boolean',
            'abdomen_esplenomeg' => 'boolean',
            'abdomen_cagabd' => 'boolean',
            'abdomen_normal' => 'boolean',
            'abdomen_text' => 'nullable|string',
            'urugenital_normal' => 'boolean',
            'urugenital_hematuria' => 'boolean',
            'urugenital_orturvias' => 'boolean',
            'urugenital_gvesical' => 'boolean',
            'urugenital_svesical' => 'boolean',
            'urugenital_guyon' => ['required', Rule::in(config('data.respiratorio')),],
            'urugenital_text' => 'nullable|string',
            'ginecobstet_normal' => 'boolean',
            'ginecobstet_embarazo' => 'boolean',
            'ginecobstet_amenazapp' => 'boolean',
            'ginecobstet_aaborto' => 'boolean',
            'ginecobstet_roturapm' => 'boolean',
            'ginecobstet_dolhipog' => 'boolean',
            'ginecobstet_genitor' => 'boolean',
            'ginecobstet_flujo' => 'boolean',
            'ginecobstet_text' => 'nullable|string',
            'siquiatrico_iae' => 'boolean',
            'siquiatrico_normal' => 'boolean',
            'siquiatrico_angustia' => 'boolean',
            'siquiatrico_depresion' => 'boolean',
            'siquiatrico_agresivo' => 'boolean',
            'siquiatrico_psicdelag' => 'boolean',
            'osteorarticular_normal' => 'boolean',
            'osteorarticular_text' => 'nullable|string',
            'signosvitales_hora1' => 'date_format:H:i',
            'signosvitales_hora2' => 'date_format:H:i',
            'signosvitales_hora3' => 'date_format:H:i',
            'signosvitales_pas1' => 'integer|between:1,15',
            'signosvitales_pas2' => 'integer|between:1,15',
            'signosvitales_pas3' => 'integer|between:1,15',
            'signosvitales_pad1' => 'integer|between:1,15',
            'signosvitales_pad2' => 'integer|between:1,15',
            'signosvitales_pad3' => 'integer|between:1,15',
            'signosvitales_temp1' => 'numeric',
            'signosvitales_temp2' => 'numeric',
            'signosvitales_temp3' => 'numeric',
            'signosvitales_frcard1' => 'integer|between:1,15',
            'signosvitales_frcard2' => 'integer|between:1,15',
            'signosvitales_frcard3' => 'integer|between:1,15',
            'signosvitales_frres1' => 'integer|between:1,15',
            'signosvitales_frres2' => 'integer|between:1,15',
            'signosvitales_frres3' => 'integer|between:1,15',
            'procedimientos_text' => 'nullable|string',
            'procedimientos_ninguno' => 'boolean',
            'medicacion_text' => 'nullable|string',
            'medicacion_ninguna' => 'boolean',
            'informe_text' => 'nullable|string',
            'diagnostico_presuntivo_codigo1' => 'string',
            'diagnostico_presuntivo_codigo2' => 'string',
            'diagnostico_presuntivo_uno' => 'nullable|string',
            'diagnostico_presuntivo_dos' => 'nullable|string',
            'desenlace_domicilio' => 'boolean',
            'desenlace_puerta' => 'boolean',
            'desenlace_cti' => 'boolean',
            'desenlace_rechazaint' => 'boolean',
            'desenlace_fallece' => 'boolean',
            'desenlace_llamadofalso' => 'boolean',
            'desenlace_instituciondeinternacion' => 'nullable|string',
            'evolucion_evolucion' => ['required', Rule::in(config('data.evolucion')),],
            'clasificaciondelllamados' => ['required', Rule::in(config('data.clasificacion_llamado')),],
            'ensuma' => 'nullable|string'
        ];
    }
}
